project: 
  type: website

website:
  search: 
    location: navbar
    type: overlay
    copy-button: true
  page-navigation: true
  title: "Advent Hymnals" 
  site-url: "https://adventhymnals.org" 
  repo-url: "https://github.com/adventhymnals/v3"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: ""
    center: "&copy; 2018-2023 Gospel Sounders"
  
  sidebar:
    background: "#A87A4E"
    favicon: images/favicon.ico
    pinned: false
    align: center
    tools: 
      - icon: globe
        href: https://gospelsounders.org
        text: "Gospel Sounders"
      - icon: github
        href: https://github.com/adventhymnals
        text: "Advent Hymnals"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: millenial-harp
        text: Millenial Harp
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: false


filters:
  - include-files.lua
  - quarto

  
